apiVersion: v1
kind: Service
metadata:
  name: simple-app-service-cluster-ip
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: my-server
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP