apiVersion: v1
kind: Service
metadata:
  name: simple-app-service-nodeport-ip
  namespace: dev
spec:
  type: NodePort
  selector:
    app: my-server
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP