apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-server
  labels:
    app: my-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-server
  template:
    metadata:
      labels:
        app: my-server
    spec:
      containers:
      - name: web-server-container
        image: akashkale/my-simple-kuberneties:1.0